import {
  ClerkProvider
} from '@clerk/nextjs';
import type { Metadata } from "next";
import { Libre_Baskerville, Poppins } from "next/font/google";
// import SignInModal from '../components/SignInModal';
import '@coinbase/onchainkit/styles.css';
// import { OnchainKitProvider } from '@coinbase/onchainkit';
// import { base } from 'wagmi/chains';
import { Providers } from '@/providers/WalletProvider';
import "./globals.css";

const libreBaskerville = Libre_Baskerville({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-libre-baskerville',
});

const poppins = Poppins({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider signInForceRedirectUrl={"/store"} signUpFallbackRedirectUrl={"/store"}>
      <html lang="en">
        <body
          className={`${libreBaskerville.variable} ${poppins.variable} font-libreBaskerville  antialiased bg-[#D3E5F4]"`}
        >


          <Providers>{children}</Providers>

        </body>
      </html>
    </ClerkProvider>
  );
}
