import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
import type { Metadata } from "next";
import { Poppins, Varela_Round } from "next/font/google";
import SignInModal from './components/SignInModal';
import "./globals.css";

const varelaRound = Varela_Round({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-varela-round',
});

const poppins = Poppins({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider signInFallbackRedirectUrl="/store"
      signUpFallbackRedirectUrl="/store">
      <html lang="en">
        <body
          className={`${varelaRound.variable} ${poppins.variable} font-poppins antialiased`}
        >
          <div className="fixed top-4 right-4 z-50">
            <SignedOut>
              <SignInModal />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </div>
          <div className="relative z-10 flex items-center justify-center min-h-screen w-full">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
